/** Studio control labels (mirrors src/lib/i18n.js keys batch.sizeLabel, video.genAudio). */
export const CONTROL_STRINGS = {
  batchSizeLabel: 'Batch size',
  genAudio: 'Gen audio',
  audio: 'Audio',
  audioOn: 'On',
  audioOff: 'Off',
  generating: 'Generating…',
  generationFailed: 'Generation failed',
  retry: 'Retry',
  retryAria: 'Retry generation with the same settings',
  recreate: 'Recreate',
  recreateAria: 'Recreate with same settings and references',
  refsMissingRecreate: 'Re-upload reference images — session previews expired.',
  seed: 'Seed',
  seedRandom: 'Randomize seed',
  seedPlaceholder: 'Random',
  seedNextHint: 'Empty = random; +1 after each success',
  openDetails: 'Open details',
  openDetailsAria: 'Open generation details',
  generationDetails: 'Generation details',
  references: 'References',
  settings: 'Settings',
  partialRefsWarning: 'Some reference files could not be restored. Re-upload to match the original generation.',
  reuploadRef: 'Re-upload',
  download: 'Download',
  close: 'Close',
};
